[profile.default]
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none" # do not include metadata hash in bytecode (for deterministic deployments)
use_literal_content = true # use source code
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

# Monad Configuration
eth_rpc_url="https://testnet-rpc.monad.xyz"
chain_id = 10143

# Foundry Fuzzing Configuration
[invariant]
runs = 256
depth = 50
call_override = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
